#define DCTSIZE 8
#define DCTSIZE2 8*8
#define GLOBAL(X) X
#define FAST_FLOAT float

typedef FAST_FLOAT JCOEF;
typedef JCOEF* JCOEFPTR;

//GLOBAL(void) jpeg_fdct_float(FAST_FLOAT* data);
//GLOBAL(void)
//jpeg_idct_float(JCOEFPTR coef_block, FAST_FLOAT* quantptr, FAST_FLOAT* outptr);

#if defined(_DEBUG)
// For debugging
#include <cstdio>
#endif

#include <cmath>
#include <algorithm>

// Quantization tables. Values generated by DCT get divided by these values when encoding

// Standard JPEG quantization tables, defined for Q=50
// These depend on standard JPEG scaling of DCT coefficients
static const unsigned int std_luminance_quant_tbl[DCTSIZE2] = {
  16,  11,  10,  16,  24,  40,  51,  61,
  12,  12,  14,  19,  26,  58,  60,  55,
  14,  13,  16,  24,  40,  57,  69,  56,
  14,  17,  22,  29,  51,  87,  80,  62,
  18,  22,  37,  56,  68, 109, 103,  77,
  24,  35,  55,  64,  81, 104, 113,  92,
  49,  64,  78,  87, 103, 121, 120, 101,
  72,  92,  95,  98, 112, 100, 103,  99
};
static const unsigned int std_chrominance_quant_tbl[DCTSIZE2] = {
  17,  18,  24,  47,  99,  99,  99,  99,
  18,  21,  26,  66,  99,  99,  99,  99,
  24,  26,  56,  99,  99,  99,  99,  99,
  47,  66,  99,  99,  99,  99,  99,  99,
  99,  99,  99,  99,  99,  99,  99,  99,
  99,  99,  99,  99,  99,  99,  99,  99,
  99,  99,  99,  99,  99,  99,  99,  99,
  99,  99,  99,  99,  99,  99,  99,  99
};

// Generates standard quantization tables based on Q
// Output values vary between 1 and 6050 (at Q<=1) for luma
// and 1 to 4950 for chroma

// JFIF baseline stores these as byte, limited to 255
void Q_table(unsigned int* table, const unsigned int *src = std_luminance_quant_tbl, int Q = 50) {

    // Convert Q to scaling factor, as in libjpeg
    /* Safety limit on quality factor.  Convert 0 to 1 to avoid zero divide. */
    if (Q <= 0) Q = 1;
    if (Q > 100) Q = 100;

    /* The basic table is used as-is (scaling 100) for a Q of 50.
     * Qualities 50..100 are converted to scaling percentage 200 - 2*Q;
     * note that at Q=100 the scaling is 0, which will cause jpeg_add_quant_table
     * to make all the table entries 1 (hence, minimum quantization loss).
     * Qualities 1..50 are converted to scaling percentage 5000/Q.
     */
    unsigned int scaling_factor = 200 - Q * 2;
    if (Q < 50)
        scaling_factor = 5000 / Q;
    
    for (int i = 0; i < DCTSIZE2; i++) {
        unsigned int temp = (scaling_factor * src[i] + 50) / 100;
        /* limit the values to the valid range */
        if (temp <= 0L) temp = 1L;

        //if (temp > 32767L) temp = 32767L; /* max quantizer needed for 12 bits */
        //if (force_baseline && temp > 255L)
        //    temp = 255L;		/* limit to baseline range if requested */

        table[i] = (unsigned int)(temp);
    }
}

// Prints an 8x8 array of doubles
void dump_float_array(FAST_FLOAT *a, const char *format = "%.1f,") {
//    return;
    for (int y = 0; y < 8; y++) {
        for (int x = 0; x < 8; x++)
            printf(format, a[y * 8 + x]);
        printf("\n");
    }
}

// For floating point scaling factors to integer values stored, see
// jcdctmgr.c, which contains:
//
//    /* For float AA&N IDCT method, divisors are equal to quantization
//     * coefficients scaled by scalefactor[row]*scalefactor[col], where
//     *   scalefactor[0] = 1
//     *   scalefactor[k] = cos(k*PI/16) * sqrt(2)    for k=1..7
//     * We apply a further scale factor of 8.
//     * What's actually stored is 1/divisor so that the inner loop can
//     * use a multiplication rather than a division.
//     */
//  FAST_FLOAT* fdtbl;
//  int row, col;
//  static const double aanscalefactor[DCTSIZE] = {
//      1.0, 1.387039845, 1.306562965, 1.175875602,
//      1.0, 0.785694958, 0.541196100, 0.275899379
//  };
//
//  if (fdct->float_divisors[qtblno] == NULL) {
//    fdct->float_divisors[qtblno] = (FAST_FLOAT*)
//      (*cinfo->mem->alloc_small) ((j_common_ptr)cinfo, JPOOL_IMAGE,
//        DCTSIZE2 * SIZEOF(FAST_FLOAT));
//  }
//  fdtbl = fdct->float_divisors[qtblno];
//  i = 0;
//  for (row = 0; row < DCTSIZE; row++) {
//    for (col = 0; col < DCTSIZE; col++) {
//      fdtbl[i] = (FAST_FLOAT)
//          (1.0 / (((double)qtbl->quantval[i] *
//            aanscalefactor[row] * aanscalefactor[col] * 8.0)));
//      i++;
//    }
//  }

static const double aanscalefactor[DCTSIZE] = {
    1.0, 1.387039845, 1.306562965, 1.175875602,
    1.0, 0.785694958, 0.541196100, 0.275899379
};

// Extra precision for the DCT results, before conversion to int, 

// to generate lossless results for 8 bit data
// Scaling is not correct
#define FACTOR 1

// From jfdctflt.c
GLOBAL(void)
jpeg_fdct_float(FAST_FLOAT* data, const FAST_FLOAT *coeff)
{
    FAST_FLOAT tmp0, tmp1, tmp2, tmp3, tmp4, tmp5, tmp6, tmp7;
    FAST_FLOAT tmp10, tmp11, tmp12, tmp13;
    FAST_FLOAT z1, z2, z3, z4, z5, z11, z13;
    FAST_FLOAT* dataptr;

    /* Pass 1: process rows. */

    dataptr = data;
    for (int r = 0; r < DCTSIZE; r++) {
        tmp0 = dataptr[0] + dataptr[7];
        tmp7 = dataptr[0] - dataptr[7];
        tmp1 = dataptr[1] + dataptr[6];
        tmp6 = dataptr[1] - dataptr[6];
        tmp2 = dataptr[2] + dataptr[5];
        tmp5 = dataptr[2] - dataptr[5];
        tmp3 = dataptr[3] + dataptr[4];
        tmp4 = dataptr[3] - dataptr[4];

        /* Even part */

        tmp10 = tmp0 + tmp3;	/* phase 2 */
        tmp13 = tmp0 - tmp3;
        tmp11 = tmp1 + tmp2;
        tmp12 = tmp1 - tmp2;
        z1 = (tmp12 + tmp13) * ((FAST_FLOAT)0.707106781); /* c4 */

        dataptr[0] = tmp10 + tmp11; /* phase 3 */
        dataptr[4] = tmp10 - tmp11;
        dataptr[2] = tmp13 + z1;	/* phase 5 */
        dataptr[6] = tmp13 - z1;

        /* Odd part */

        tmp10 = tmp4 + tmp5;	/* phase 2 */
        tmp11 = tmp5 + tmp6;
        tmp12 = tmp6 + tmp7;

        /* The rotator is modified from fig 4-8 to avoid extra negations. */
        z5 = (tmp10 - tmp12) * ((FAST_FLOAT)0.382683433); /* c6 */
        z2 = ((FAST_FLOAT)0.541196100) * tmp10 + z5; /* c2-c6 */
        z4 = ((FAST_FLOAT)1.306562965) * tmp12 + z5; /* c2+c6 */
        z3 = tmp11 * ((FAST_FLOAT)0.707106781); /* c4 */

        z13 = tmp7 - z3;        /* phase 5 */
        z11 = tmp7 + z3;

        dataptr[5] = z13 + z2;	/* phase 6 */
        dataptr[3] = z13 - z2;
        dataptr[1] = z11 + z4;
        dataptr[7] = z11 - z4;

        dataptr += DCTSIZE;		/* advance pointer to next row */
    }

    /* Pass 2: process columns. */

    dataptr = data;
    for (int c = 0; c < DCTSIZE; c++) {
        // pointer to the coefficients for this column
        const FAST_FLOAT* co = coeff + c * DCTSIZE;

        tmp0 = dataptr[DCTSIZE * 0] + dataptr[DCTSIZE * 7];
        tmp7 = dataptr[DCTSIZE * 0] - dataptr[DCTSIZE * 7];
        tmp1 = dataptr[DCTSIZE * 1] + dataptr[DCTSIZE * 6];
        tmp6 = dataptr[DCTSIZE * 1] - dataptr[DCTSIZE * 6];
        tmp2 = dataptr[DCTSIZE * 2] + dataptr[DCTSIZE * 5];
        tmp5 = dataptr[DCTSIZE * 2] - dataptr[DCTSIZE * 5];
        tmp3 = dataptr[DCTSIZE * 3] + dataptr[DCTSIZE * 4];
        tmp4 = dataptr[DCTSIZE * 3] - dataptr[DCTSIZE * 4];

        /* Even part */
        tmp10 = tmp0 + tmp3;	/* phase 2 */
        tmp13 = tmp0 - tmp3;
        tmp11 = tmp1 + tmp2;
        tmp12 = tmp1 - tmp2;
        z1 = (tmp12 + tmp13) * ((FAST_FLOAT)0.707106781); /* c4 */

        // dataptr[DCTSIZE * 0] = tmp10 + tmp11; /* phase 3 */
        // dataptr[DCTSIZE * 4] = tmp10 - tmp11;
        dataptr[DCTSIZE * 0] = co[0] * (tmp10 + tmp11);
        dataptr[DCTSIZE * 4] = co[4] * (tmp10 - tmp11) ;
        dataptr[DCTSIZE * 2] = co[2] * (tmp13 + z1); /* phase 5 */
        dataptr[DCTSIZE * 6] = co[6] * (tmp13 - z1);

        /* Odd part */

        tmp10 = tmp4 + tmp5;	/* phase 2 */
        tmp11 = tmp5 + tmp6;
        tmp12 = tmp6 + tmp7;

        /* The rotator is modified from fig 4-8 to avoid extra negations. */
        z5 = (tmp10 - tmp12) * ((FAST_FLOAT)0.382683433); /* c6 */
        z2 = ((FAST_FLOAT)0.541196100) * tmp10 + z5; /* c2-c6 */
        z4 = ((FAST_FLOAT)1.306562965) * tmp12 + z5; /* c2+c6 */
        z3 = tmp11 * ((FAST_FLOAT)0.707106781); /* c4 */

        z11 = tmp7 + z3;		/* phase 5 */
        z13 = tmp7 - z3;

        dataptr[DCTSIZE * 5] = co[5] * (z13 + z2); /* phase 6 */
        dataptr[DCTSIZE * 3] = co[3] * (z13 - z2);
        dataptr[DCTSIZE * 1] = co[1] * (z11 + z4);
        dataptr[DCTSIZE * 7] = co[7] * (z11 - z4);

        dataptr++;			/* advance pointer to next column */
    }
}

// From jidctflt.c

/* Dequantize a coefficient by multiplying it by the multiplier-table
 * entry; produce a float result.
 */
#define DEQUANTIZE(coef, quantval)  (((FAST_FLOAT) (coef)) * (quantval))

 /*
  * Perform dequantization and inverse DCT on one block of coefficients.
  */
GLOBAL(void)
jpeg_idct_float(JCOEFPTR coef_block, const FAST_FLOAT* quantptr, FAST_FLOAT* output)
{
    FAST_FLOAT tmp0, tmp1, tmp2, tmp3, tmp4, tmp5, tmp6, tmp7;
    FAST_FLOAT tmp10, tmp11, tmp12, tmp13;
    FAST_FLOAT z5, z10, z11, z12, z13;
    FAST_FLOAT workspace[DCTSIZE * DCTSIZE]; /* buffers data between passes */
    FAST_FLOAT* wsptr = workspace;

    /* Pass 1: process columns from input, store into work array. */

    JCOEFPTR inptr = coef_block;
    for (int ctr = 0; ctr < DCTSIZE; ctr++) {
        /* Due to quantization, we will usually find that many of the input
         * coefficients are zero, especially the AC terms.  We can exploit this
         * by short-circuiting the IDCT calculation for any column in which all
         * the AC terms are zero.  In that case each output is equal to the
         * DC coefficient (with scale factor as needed).
         * With typical images and quantization tables, half or more of the
         * column DCT calculations can be simplified this way.
         */

        if (inptr[DCTSIZE * 1] == 0 && inptr[DCTSIZE * 2] == 0 &&
            inptr[DCTSIZE * 3] == 0 && inptr[DCTSIZE * 4] == 0 &&
            inptr[DCTSIZE * 5] == 0 && inptr[DCTSIZE * 6] == 0 &&
            inptr[DCTSIZE * 7] == 0) {
            /* AC terms all zero */
            FAST_FLOAT dcval = DEQUANTIZE(inptr[DCTSIZE * 0], quantptr[DCTSIZE * 0]);

            wsptr[DCTSIZE * 0] = dcval;
            wsptr[DCTSIZE * 1] = dcval;
            wsptr[DCTSIZE * 2] = dcval;
            wsptr[DCTSIZE * 3] = dcval;
            wsptr[DCTSIZE * 4] = dcval;
            wsptr[DCTSIZE * 5] = dcval;
            wsptr[DCTSIZE * 6] = dcval;
            wsptr[DCTSIZE * 7] = dcval;

            inptr++;			/* advance pointers to next column */
            quantptr++;
            wsptr++;
            continue;
        }

        /* Even part */

        tmp0 = DEQUANTIZE(inptr[DCTSIZE * 0], quantptr[DCTSIZE * 0]);
        tmp1 = DEQUANTIZE(inptr[DCTSIZE * 2], quantptr[DCTSIZE * 2]);
        tmp2 = DEQUANTIZE(inptr[DCTSIZE * 4], quantptr[DCTSIZE * 4]);
        tmp3 = DEQUANTIZE(inptr[DCTSIZE * 6], quantptr[DCTSIZE * 6]);

        tmp10 = tmp0 + tmp2;	/* phase 3 */
        tmp11 = tmp0 - tmp2;

        tmp13 = tmp1 + tmp3;	/* phases 5-3 */
        tmp12 = (tmp1 - tmp3) * ((FAST_FLOAT)1.414213562) - tmp13; /* 2*c4 */

        tmp0 = tmp10 + tmp13;	/* phase 2 */
        tmp3 = tmp10 - tmp13;
        tmp1 = tmp11 + tmp12;
        tmp2 = tmp11 - tmp12;

        /* Odd part */

        tmp4 = DEQUANTIZE(inptr[DCTSIZE * 1], quantptr[DCTSIZE * 1]);
        tmp5 = DEQUANTIZE(inptr[DCTSIZE * 3], quantptr[DCTSIZE * 3]);
        tmp6 = DEQUANTIZE(inptr[DCTSIZE * 5], quantptr[DCTSIZE * 5]);
        tmp7 = DEQUANTIZE(inptr[DCTSIZE * 7], quantptr[DCTSIZE * 7]);

        z13 = tmp6 + tmp5;		/* phase 6 */
        z10 = tmp6 - tmp5;
        z11 = tmp4 + tmp7;
        z12 = tmp4 - tmp7;

        tmp7 = z11 + z13;		/* phase 5 */
        tmp11 = (z11 - z13) * ((FAST_FLOAT)1.414213562); /* 2*c4 */

        z5 = (z10 + z12) * ((FAST_FLOAT)1.847759065); /* 2*c2 */
        tmp10 = ((FAST_FLOAT)1.082392200) * z12 - z5; /* 2*(c2-c6) */
        tmp12 = ((FAST_FLOAT)-2.613125930) * z10 + z5; /* -2*(c2+c6) */

        tmp6 = tmp12 - tmp7;	/* phase 2 */
        tmp5 = tmp11 - tmp6;
        tmp4 = tmp10 + tmp5;

        wsptr[DCTSIZE * 0] = tmp0 + tmp7;
        wsptr[DCTSIZE * 1] = tmp1 + tmp6;
        wsptr[DCTSIZE * 2] = tmp2 + tmp5;
        wsptr[DCTSIZE * 3] = tmp3 - tmp4;
        wsptr[DCTSIZE * 4] = tmp3 + tmp4;
        wsptr[DCTSIZE * 5] = tmp2 - tmp5;
        wsptr[DCTSIZE * 6] = tmp1 - tmp6;
        wsptr[DCTSIZE * 7] = tmp0 - tmp7;

        inptr++;			/* advance pointers to next column */
        quantptr++;
        wsptr++;
    }

    /* Pass 2: process rows from work array, store into output array. */
    for (int ctr = 0; ctr < DCTSIZE; ctr++) {
        FAST_FLOAT* outptr = output + ctr * DCTSIZE;
        wsptr = workspace + ctr * DCTSIZE;
        /* Rows of zeroes can be exploited in the same way as we did with columns.
         * However, the column calculation has created many nonzero AC terms, so
         * the simplification applies less often (typically 5% to 10% of the time).
         * And testing floats for zero is relatively expensive, so we don't bother.
         */

         /* Even part */
        tmp10 = wsptr[0] + wsptr[4];
        tmp11 = wsptr[0] - wsptr[4];

        tmp13 = wsptr[2] + wsptr[6];
        tmp12 = (wsptr[2] - wsptr[6]) * ((FAST_FLOAT)1.414213562) - tmp13;

        tmp0 = tmp10 + tmp13;
        tmp3 = tmp10 - tmp13;
        tmp1 = tmp11 + tmp12;
        tmp2 = tmp11 - tmp12;

        /* Odd part */

        z13 = wsptr[5] + wsptr[3];
        z10 = wsptr[5] - wsptr[3];
        z11 = wsptr[1] + wsptr[7];
        z12 = wsptr[1] - wsptr[7];

        tmp7 = z11 + z13;
        tmp11 = (z11 - z13) * ((FAST_FLOAT)1.414213562);

        z5 = (z10 + z12) * ((FAST_FLOAT)1.847759065); /* 2*c2 */
        tmp10 = ((FAST_FLOAT)1.082392200) * z12 - z5; /* 2*(c2-c6) */
        tmp12 = ((FAST_FLOAT)-2.613125930) * z10 + z5; /* -2*(c2+c6) */

        tmp6 = tmp12 - tmp7;
        tmp5 = tmp11 - tmp6;
        tmp4 = tmp10 + tmp5;

        *outptr++ = tmp0 + tmp7;
        *outptr++ = tmp1 + tmp6;
        *outptr++ = tmp2 + tmp5;
        *outptr++ = tmp3 - tmp4;
        *outptr++ = tmp3 + tmp4;
        *outptr++ = tmp2 - tmp5;
        *outptr++ = tmp1 - tmp6;
        *outptr++ = tmp0 - tmp7;
    }
}

int main(int argc, char** argv) {

#define NBITS 12
    const int MAXVAL = 1 << NBITS;
    // For dequantization
    unsigned int uiqtable[64];
    //for (int i = 0; i < 64; i++)
    //    qtable[i] = 1;

    Q_table(uiqtable, std_luminance_quant_tbl, 100);
    FAST_FLOAT qtable[64];
    for (int i = 0; i < 64; i++)
        qtable[i] = int(round(uiqtable[i]));

    //for (int i = 0; i < 64; i++)
    //    qtable[i] /= 64.0 * FACTOR;


    // Example from wikipedia
    FAST_FLOAT data[64] = {
        52,55,61,66,70,61,64,73,
        63,59,55,90,109,85,69,72,
        62,59,68,113,144,104,66,73,
        63,58,71,122,154,106,70,69,
        67,61,68,104,126,88,68,70,
        79,65,60,70,77,68,58,75,
        85,71,64,59,55,61,65,83,
        87,79,69,68,65,76,78,94
    };


    // Bias around 0. This only affects the constant value (DCT[0]), it's not really needed
    // Without it, an extra bit might be needed for temporary values
    // 
    // for (int i = 0; i < 64; i++)
    //    data[i] -= 128;

    for (int i = 0; i < 64; i++)
        data[i] = !(i & 0b1001) ? 0 : (MAXVAL - 1);

    //for (int y = 0; y < 8; y++)
    //    for (int x = 0; x < 8; x++)
    //        data[y * 8 + x] = FAST_FLOAT(0 * x + 0 * y);
    //data[3 * 8 + 4] = 65535;
    //data[5 * 8 + 6] = 4095;

    int original_data[64];
    for (int i = 0; i < 64; i++)
        original_data[i] = int(data[i]);

    printf("Start\n");
    dump_float_array(data);

    // Build multiplication coefficients libjpeg style, taking into account qtable
    // Table with scaling values for the DCT results. Stored in column major order for speed
    FAST_FLOAT coefficients[DCTSIZE2];
    for (int r = 0; r < DCTSIZE; r++)
        for (int c = 0; c < DCTSIZE; c++)
            coefficients[c * DCTSIZE + r] = 1.0 / (qtable[r * DCTSIZE + c] * aanscalefactor[r] * aanscalefactor[c] * 8.0);

    jpeg_fdct_float(data, coefficients);

    // Round to int, as stored
    for (int i = 0; i < 64; i++)
        data[i] = int(round(data[i]));

    //printf("Out\n");
    //dump_float_array(data, "%.0f,");

    FAST_FLOAT data_out[64];

    // Dequantization table, stored in standard order, row major
    FAST_FLOAT dqtable[DCTSIZE2];
    for (int r = 0; r < DCTSIZE; r++)
        for (int c = 0; c < DCTSIZE; c++)
            dqtable[r * DCTSIZE + c] = 1.0 / (64 * coefficients[c * DCTSIZE + r]);

    //printf("DQTable\n");
    //dump_float_array(dqtable, "%.2f,");

    jpeg_idct_float(data, dqtable, data_out);

    //printf("Back\n");
    //dump_float_array(data_out, "%.19f,");

    int out_data[64];
    for (int i = 0; i < 64; i++)
        out_data[i] = std::max<int>(0, std::min<int>(MAXVAL, int(data_out[i] + 0.5))); // Round and clip

    // Test that out_data == original_data
    for (int i = 0; i < 64; i++)
        if (out_data[i] != original_data[i])
            printf("Error at index %d, got %d, expected %d, delta %d\n", i, out_data[i], original_data[i], - out_data[i] + original_data[i]);
}