#!/bin/bash

#Build qb3-wasm decoder as an JS6 module using emscripten
# Assume libQB3.a is already built and available in the current folder
# Assume json.hpp is in the include path for emcc

OPTS="-O3 -flto"
# Standard emscripten functions
EXPORTS=_malloc,_free

# Place json.hpp in the current folder
emcc $OPTS -I . -c qb3decapi.cpp

#Build qb3-wasm module, see post.js for API
emcc $OPTS -o qb3-wasm.mjs qb3decapi.o libQB3.a \
    -s EXPORTED_FUNCTIONS=$EXPORTS \
    -s NO_EXIT_RUNTIME=1 \
    -s ALLOW_MEMORY_GROWTH=1 \
    --no-entry \
    --post-js post.js \
    -sENVIRONMENT=web,worker \
    -sEXPORTED_RUNTIME_METHODS=[ccall,writeArrayToMemory,UTF8ToString]
